=== mfamador/search/search-core/src/main/resources/META-INF/search-metadata_1_5.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!--
     DTD Search MetaData 1.5

     Para suportar a validação do teu ficheiro de configuração, inclui
     o seguinte DOCTYPE no início do teu ficheiro XML (depois da declaração 
     "xml"):

     <!DOCTYPE search-metadata PUBLIC 
               "-//Maisis//DTD Search MetaData 1.5//EN" 
               "http://www.maisis.pt/search/dtds/search-metadata_1_5.dtd">
-->

<!ENTITY % script 
  "#PCDATA">

<!ENTITY % boolean
  "#PCDATA">

<!ELEMENT search-metadata
  (name,
   label,
   description,
   search-engine-class?,
   data-source?,
   search-result-exporter?,
   (table-source|sql-template),
   properties?,
   search-params?,
   result-params,
   required-result-params*,
   selected-result-params*,
   selected-result-params-order*)>

<!ELEMENT search-result-exporter
  (class, 
  template,
  is-velocity-template)>

<!ELEMENT search-params
  ((search-param | dynamic-search-params)+,
  search-sql-fragment?)>

<!ELEMENT result-params
  (result-param | composite-result-param | dynamic-result-params)+>

<!ELEMENT required-result-params
  (required-result-param | dynamic-required-result-params)+>

<!ELEMENT selected-result-params
  (selected-result-param | dynamic-selected-result-params)+>

<!ELEMENT selected-result-params-order
  (selected-result-param-order)+>

<!ELEMENT selected-result-param-order
  (name, order-type?)>

<!ELEMENT search-param
  (name,
   field,
   operator,
   (composite-container|container),
   properties?)>

<!ELEMENT search-sql-fragment
  (name,
   value?)>

<!ELEMENT properties
  (property)+>

<!ELEMENT property
  (name, value)>

<!ELEMENT dynamic-search-params
  EMPTY>

<!ELEMENT dynamic-result-params
  EMPTY>

<!ELEMENT dynamic-required-result-params
  EMPTY>

<!ELEMENT dynamic-selected-result-params
  EMPTY>

<!ATTLIST dynamic-search-params
  class CDATA #REQUIRED>

<!ATTLIST dynamic-result-params
  class CDATA #REQUIRED>

<!ATTLIST dynamic-required-result-params
  class CDATA #REQUIRED>

<!ATTLIST dynamic-selected-result-params
  class CDATA #REQUIRED>

<!ELEMENT composite-container
  (label?,
   label-orientation?,
   validation?,
   formatter?,
   fragment-container+)>

<!ELEMENT container
  (label?,
   label-orientation?,
   type?,
   checked?,
   disabled?,
   readonly?,
   size?,
   input-size?,
   (default-value-constant | default-value-expression | default-value-list)?,
   ajax?,
   validation?,
   event?)>

<!ELEMENT fragment-container
  (name,
   label?,
   label-orientation?,
   type?,
   checked?,
   disabled?,
   readonly?,
   size?,
   input-size?,
   (default-value-constant | default-value-expression | default-value-list)?,
   ajax?,
   validation?,
   event?)>

<!ELEMENT event
  (onclick?,
   ondblclick?,
   onmousedown?,
   onmouseup?,
   onmouseover?,
   onmousemove?,
   onmouseout?,
   onfocus?,
   onblur?,
   onkeypress?,
   onkeydown?,
   onkeyup?,
   onchange?)>

<!ELEMENT default-value-list
  (sql|constants)>

<!ELEMENT ajax
  (sql,
   source,
   parameters)>

<!ELEMENT parameters
  (parameter+)>

<!ELEMENT constants
  (constant+)>

<!ELEMENT constant
  (key,
   value?,
   selected?)>

<!ELEMENT sql 
  (data-source?,
   statement,
   column-mapping?,
   selected-keys?)>

<!ELEMENT column-mapping 
  (key,
   value)>

<!ELEMENT selected-keys 
  (key+)>

<!ELEMENT result-param
  (name,
   selectable?,
   search-label?,
   result-label?,
   fields,
   align?,
   width?,
   height?,
   header-style?,
   value-style?,
   formatter?,
   exporter-formatter?,
   properties?)>

<!ELEMENT composite-result-param
  (name,
   selectable?,
   search-label?,
   result-label?,
   align?,
   width?,
   height?,
   header-style?,
   result-param+,
   composite-result-param*,
   properties?)>

<!ELEMENT required-result-param
  (name,
   fields,
   properties?,
   depends?,
   unless?)>
    
<!ELEMENT formatter
  (name?, pattern?, null-value?)>

<!ELEMENT exporter-formatter
  (name?, pattern?, null-value?)>

<!ELEMENT validation
  (converter?, 
   converter-properties?,
   required?, 
   min-length?, 
   max-length?, 
   min-value?, 
   max-value?, 
   regex?, 
   expression?)>

<!ELEMENT converter-properties
  (property+)>

<!ELEMENT fields
  (field+)>

<!ELEMENT selected                 (%boolean;)>
<!ELEMENT required                 (%boolean;)>
<!ELEMENT converter                (#PCDATA)>
<!ELEMENT min-length               (#PCDATA)>
<!ELEMENT max-length               (#PCDATA)>
<!ELEMENT min-value                (#PCDATA)>
<!ELEMENT max-value                (#PCDATA)>
<!ELEMENT regex                    (#PCDATA)>
<!ELEMENT expression               (#PCDATA)>
<!ELEMENT name                     (#PCDATA)>
<!ELEMENT value                    (#PCDATA)>
<!ELEMENT description              (#PCDATA)>
<!ELEMENT search-engine-class      (#PCDATA)>
<!ELEMENT data-source              (#PCDATA)>
<!ELEMENT table-source             (#PCDATA)>
<!ELEMENT sql-template             (#PCDATA)>
<!ELEMENT field                    (#PCDATA)>
<!ELEMENT operator                 (#PCDATA)>
<!ELEMENT class                    (#PCDATA)>
<!ELEMENT template                 (#PCDATA)>
<!ELEMENT pattern                  (#PCDATA)>
<!ELEMENT join-pattern             (#PCDATA)>
<!ELEMENT join-token               (#PCDATA)>
<!ELEMENT input-size               (#PCDATA)>
<!ELEMENT label                    (#PCDATA)>
<!ELEMENT label-orientation        (#PCDATA)>
<!ELEMENT default-value-constant   (#PCDATA)>
<!ELEMENT default-value-expression (#PCDATA)>
<!ELEMENT search-label             (#PCDATA)>
<!ELEMENT result-label             (#PCDATA)>
<!ELEMENT displayable              (#PCDATA)>
<!ELEMENT align                    (#PCDATA)>
<!ELEMENT size                     (#PCDATA)>
<!ELEMENT width                    (#PCDATA)>
<!ELEMENT height                   (#PCDATA)>
<!ELEMENT depends                  (#PCDATA)>
<!ELEMENT unless                   (#PCDATA)>
<!ELEMENT selected-result-param    (#PCDATA)>
<!ELEMENT order-type               (#PCDATA)>
<!ELEMENT type                     (#PCDATA)>
<!ELEMENT checked                  (#PCDATA)>
<!ELEMENT disabled                 (#PCDATA)>
<!ELEMENT readonly                 (#PCDATA)>
<!ELEMENT is-velocity-template     (#PCDATA)>
<!ELEMENT selectable               (#PCDATA)>
<!ELEMENT statement                (#PCDATA)>
<!ELEMENT key                      (#PCDATA)>
<!ELEMENT source                   (#PCDATA)>
<!ELEMENT parameter                (#PCDATA)>
<!ELEMENT header-style             (#PCDATA)>
<!ELEMENT value-style              (#PCDATA)>
<!ELEMENT null-value               (#PCDATA)>

<!ELEMENT onclick                  (%script;)>
<!ELEMENT ondblclick               (%script;)>
<!ELEMENT onmousedown              (%script;)>
<!ELEMENT onmouseup                (%script;)>
<!ELEMENT onmouseover              (%script;)>
<!ELEMENT onmousemove              (%script;)>
<!ELEMENT onmouseout               (%script;)>
<!ELEMENT onfocus                  (%script;)>
<!ELEMENT onblur                   (%script;)>
<!ELEMENT onkeypress               (%script;)>
<!ELEMENT onkeydown                (%script;)>
<!ELEMENT onkeyup                  (%script;)>
<!ELEMENT onchange                 (%script;)>

=== mfamador/search/search-example/src/main/resources/search-example-3.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!DOCTYPE search-metadata PUBLIC 
"-//Maisis//DTD Search MetaData 1.5//EN" 
"http://www.maisis.pt/search/dtds/search-metadata_1_5.dtd">

<search-metadata>
  <name>search3</name>
  <label>Exemplo ajax</label>
  <description>...</description>
  <table-source>UTILIZADOR_VIEW</table-source>
  
  <!-- search params -->
  <search-params>
    <search-param>
      <name>nome</name>
      <field>upper(NOME)</field>
      <operator>LIKE</operator>
      <container>
        <label>Nome</label>
        <type>text</type>
        <size>160</size>
        <input-size>50</input-size>
        <ajax>
          <sql>
            <statement>select nome, nome from utilizador_view where nome like ?</statement>
          </sql>
          <source>nome</source>
          <parameters>
            <parameter>nome</parameter>
          </parameters>
        </ajax>
        <validation>
          <converter>sqllike</converter>
        </validation>
      </container>
    </search-param>
    
    <search-param>
      <name>numero</name>
      <field>NUM_EMPREGADO</field>
      <operator>IN</operator>
      <container>
        <label>Num</label>
        <type>text</type>
        <size>160</size>
        <input-size>50</input-size>
        <validation>
          <converter>split</converter>
        </validation>
      </container>
    </search-param>
    
    <search-param>
      <name>tipoUtilizador</name>
      <field>ID_TIPO_UTILIZADOR</field>
      <operator>=</operator>
      <container>
        <label>Tipo</label>
        <type>select</type>
        <size>95</size>
        <default-value-list>
          <sql>
            <statement>select id, nome from tipo_utilizador</statement>
          </sql>
        </default-value-list>
      </container>
    </search-param>
    
    <search-param>
      <name>nomeUtilizador</name>
      <field>NOME</field>
      <operator>LIKE</operator>
      <container>
        <label>Utilizador</label>
        <type>select</type>
        <size>95</size>
        <ajax>
          <sql>
            <statement>select nome, nome as label from utilizador_view where id_tipo_utilizador in (#)</statement>
          </sql>
          <source>tipoUtilizador</source>
          <parameters>
            <parameter>tipoUtilizador_multipleResult_hidden</parameter>
         </parameters>
       </ajax>
      </container>
    </search-param>
 
    <search-param>
      <name>data</name>
      <field>DATA</field>
      <operator>=</operator>
      
      <composite-container>
        <label>Data</label>
        <validation>
          <converter>sqldate</converter>
          <converter-properties>
            <property>
              <name>default-pattern</name>
              <value>yyMMdd</value>
            </property>
          </converter-properties>
        </validation>
        <formatter>
          <name>message</name>
          <pattern>{0}{1}{2}</pattern>
        </formatter>
        
        <fragment-container>
          <name>ano</name>
          <label>Ano</label>
          <type>select</type>
          <size>45</size>
          <input-size>4</input-size>
          <default-value-list>
            <constants>
              <constant>
                <key>07</key>
              </constant>
              <constant>
                <key>06</key>
              </constant>
              <constant>
                <key>05</key>
              </constant>
              <constant>
                <key>04</key>
              </constant>
              <constant>
                <key>03</key>
              </constant>
              <constant>
                <key>02</key>
              </constant>
              <constant>
                <key>01</key>
              </constant>
              <constant>
                <key>99</key>
              </constant>
              <constant>
                <key>98</key>
              </constant>
              <constant>
                <key>97</key>
              </constant>
              <constant>
                <key>96</key>
              </constant>
              <constant>
                <key>95</key>
              </constant>
              <constant>
                <key>94</key>
              </constant>
            </constants>
          </default-value-list>
          <validation>
            <converter>date</converter>
            <converter-properties>
              <property>
                <name>default-pattern</name>
                <value>yy</value>
              </property>
            </converter-properties>
          </validation>
        </fragment-container>
        
        <fragment-container>
          <name>mes</name>
          <label>Mês</label>
          <type>text</type>
          <size>25</size>
          <input-size>2</input-size>
          <validation>
            <converter>date</converter>
            <converter-properties>
              <property>
                <name>default-pattern</name>
                <value>MM</value>
              </property>
            </converter-properties>
          </validation>
        </fragment-container>
        
        <fragment-container>
          <name>dia</name>
          <label>Dia</label>
          <type>text</type>
          <size>25</size>
          <input-size>2</input-size>
          <validation>
            <converter>date</converter>
            <converter-properties>
              <property>
                <name>default-pattern</name>
                <value>dd</value>
              </property>
            </converter-properties>
          </validation>
        </fragment-container>
      </composite-container>
    </search-param>
  </search-params>
  
  <!-- result params -->
  <result-params>
    <result-param>
      <name>nome</name>
      <search-label>Nome</search-label>
      <fields>
        <field>NOME</field> 
      </fields>
      <align>left</align>
      <width>241</width>
      <height>30</height>
      <properties>
        <property>
          <name>field-type</name>
          <value>string-field</value>
        </property>
      </properties>
    </result-param>
    
    <composite-result-param>
      <name>composite</name>
      <search-label>Empregado</search-label>
      <height>15</height>
      
      <result-param>
        <name>numEmpregado</name>
        <search-label>Num</search-label>
        <fields>
          <field>NUM_EMPREGADO</field> 
        </fields>
        <align>center</align>
        <width>60</width>
        <height>15</height>
        <formatter>
          <null-value>-</null-value>
        </formatter>
      </result-param>
      
      <result-param>
        <name>tipoUtilizador</name>
        <search-label>Tipo</search-label>
        <fields>
          <field>TIPO</field> 
        </fields>
        <align>center</align>
        <width>60</width>
        <height>15</height>
      </result-param>
    </composite-result-param>
    
    <result-param>
      <name>data</name>
      <search-label>Data</search-label>
      <fields>
        <field>DATA</field> 
      </fields>
      <align>center</align>
      <width>60</width>
      <height>30</height>
      <formatter>
        <name>customDate</name>
        <pattern>yyyy-MM-dd</pattern>
      </formatter>
    </result-param>
  </result-params>
  
  <!-- required result params -->
  <required-result-params>
    <required-result-param>
      <name>id</name>
      <fields>
        <field>ID</field>
      </fields>
    </required-result-param>
  </required-result-params>
  
  <!-- selected result params order -->
  <selected-result-params-order>
    <selected-result-param-order>
      <name>numEmpregado</name>
      <order-type>asc</order-type>
    </selected-result-param-order>
  </selected-result-params-order>
  
</search-metadata>

=== mfamador/search/search-example/src/main/resources/search-example-2.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!DOCTYPE search-metadata PUBLIC 
"-//Maisis//DTD Search MetaData 1.5//EN" 
"http://www.maisis.pt/search/dtds/search-metadata_1_5.dtd">

<search-metadata>
  <name>search2</name>
  <label>Exemplo 2</label>
  <description>...</description>
  <search-engine-class>pt.maisis.search.dao.db.VelocitySearchEngineDao</search-engine-class>
  <sql-template>
    <![CDATA[
      select
        #if ($queryType == 'count')
          count(*)
        #else
          $sql.getCsv($resultParams)
        #end
      from 
        UTILIZADOR a,
        TIPO_UTILIZADOR b
      where
        a.ID_TIPO_UTILIZADOR = b.ID
        #if ($searchParams)
          and $sql.getCriterias($searchParams)
        #end
      #if ($orderParams)
        order by $sql.getCsv($orderParams)  
      #end
    ]]>
  </sql-template>
          
  <search-params>
    <search-param>
      <name>name</name>
      <field>upper(a.NOME)</field>
      <operator>LIKE</operator>
      <container>
        <label>label.name</label>
        <type>text</type>
        <size>290</size>
        <input-size>50</input-size>
	<validation>
	  <converter>sqllike</converter>
	</validation>
      </container>
    </search-param>

    <search-param>
      <name>startDate</name>
      <field>DATA</field>
      <operator>&gt;=</operator>

      <composite-container>
        <label>label.startDate</label>
	<validation>
	  <converter>sqldate</converter>
	  <expression><![CDATA[
	  endDate == null || startDate < endDate
	  ]]></expression>
	</validation>

        <fragment-container>
          <name>startDay</name>
          <label>label.day</label>
          <type>text</type>
          <size>30</size>
          <input-size>2</input-size>
          <validation>
	    <converter>date</converter>
	    <converter-properties>
	      <property>
		<name>pt</name>
		<value>dd</value>
	      </property>
	    </converter-properties>
	  </validation>
        </fragment-container>

        <fragment-container>
          <name>startMonth</name>
          <label>label.month</label>
          <type>text</type>
          <size>30</size>
          <input-size>2</input-size>
	  <validation>
	    <converter>date</converter>
	    <converter-properties>
	      <property>
		<name>pt</name>
		<value>MM</value>
	      </property>
	    </converter-properties>
	  </validation>
        </fragment-container>

        <fragment-container>
          <name>startYear</name>
          <label>label.year</label>
          <type>text</type>
          <size>50</size>
          <input-size>4</input-size>
	  <validation>
	    <converter>date</converter>
	    <converter-properties>
	      <property>
		<name>pt</name>
		<value>yyyy</value>
	      </property>
	    </converter-properties>
	  </validation>
        </fragment-container>
      </composite-container>
    </search-param>

    <search-param>
      <name>endDate</name>
      <field>DATA</field>
      <operator>&lt;=</operator>

      <composite-container>
        <label>label.endDate</label>
	<validation>
	  <converter>sqldate</converter>
	  <expression><![CDATA[
	  date == date
	  ]]></expression>
	</validation>

        <fragment-container>
          <name>endDay</name>
          <label>label.day</label>
          <type>text</type>
          <size>30</size>
          <input-size>2</input-size>
          <validation>
	    <converter>date</converter>
	    <converter-properties>
	      <property>
		<name>pt</name>
		<value>dd</value>
	      </property>
	    </converter-properties>
	  </validation>
        </fragment-container>

        <fragment-container>
          <name>endMonth</name>
          <label>label.month</label>
          <type>text</type>
          <size>30</size>
          <input-size>2</input-size>
	  <validation>
	    <converter>date</converter>
	    <converter-properties>
	      <property>
		<name>pt</name>
		<value>MM</value>
	      </property>
	    </converter-properties>
	  </validation>
        </fragment-container>

        <fragment-container>
          <name>endYear</name>
          <label>label.year</label>
          <type>text</type>
          <size>50</size>
          <input-size>4</input-size>
	  <validation>
	    <converter>date</converter>
	    <converter-properties>
	      <property>
		<name>pt</name>
		<value>yyyy</value>
	      </property>
	    </converter-properties>
	  </validation>
        </fragment-container>
      </composite-container>
    </search-param>
  </search-params>

  <result-params>
    <result-param>
      <name>name</name>
      <search-label>label.name</search-label>
      <fields>
        <field>a.NOME</field> 
      </fields>
      <align>left</align>
      <width>241</width>
      <height>15</height>
      <header-style>result-header</header-style>
      <value-style>result-value</value-style>
    </result-param>

    <result-param>
      <name>employe</name>
      <search-label>label.employe</search-label>
      <fields>
        <field>NUM_EMPREGADO</field> 
      </fields>
      <align>center</align>
      <width>50</width>
      <height>15</height>
      <header-style>result-header</header-style>
      <value-style>result-value</value-style>
    </result-param>
    
    <result-param>
      <name>type</name>
      <search-label>label.type</search-label>
      <fields>
        <field>b.NOME</field> 
      </fields>
      <align>center</align>
      <width>60</width>
      <height>15</height>
      <header-style>result-header</header-style>
      <value-style>result-value-2</value-style>
    </result-param>
                         
    <result-param>
      <name>date</name>
      <search-label>label.date</search-label>
      <fields>
        <field>DATA</field> 
      </fields>
      <align>center</align>
      <width>80</width>
      <height>15</height>
      <formatter>
        <name>date</name>
      </formatter>
    </result-param>

    <result-param>
      <name>phone</name>
      <search-label>label.phone</search-label>
      <fields>
        <field>TELEFONE</field> 
      </fields>
      <align>center</align>
      <width>55</width>
      <height>15</height>
    </result-param>
  </result-params>
          
  <required-result-params>
    <required-result-param>
      <name>id</name>
      <fields>
        <field>a.ID</field>
      </fields>
    </required-result-param>
  </required-result-params>

</search-metadata>

=== mfamador/search/search-core/src/test/resources/test-search.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!DOCTYPE search-metadata PUBLIC 
"-//Maisis//DTD Search MetaData 1.5//EN" 
"http://www.maisis.pt/search/dtds/search-metadata_1_5.dtd">


<search-metadata>
  <name>searchTest</name>
  <label>Search Test</label>
  <description>Search Test</description>
  <search-engine-class>pt.maisis.search.dao.db.SearchEngineDaoImpl</search-engine-class> 

  <!-- 
       Neste momento só é possível utilizar datasources via JNDI.
       
       TODO: É preciso melhorar isto.
             O melhor talvez seja possibilitar no ficheiro search-config.xml,
             definir uma, ou mais, datasources directamente.
             Depois, nos ficheiros de definição das pesquisas só se deve
             especificar o nome da datasource (JNDI name).
  -->
  <data-source>java:comp/env/jdbc/SearchDS</data-source>
  
  <table-source>SEARCH_TEST</table-source>
  
  <search-params>
        <search-param>
      <name>id</name>
      <field>ID</field>
      <operator>=</operator>
      <container>
        <label>Id</label>
        <type>text</type>
        <size>128</size>
	<validation>
	  <converter>number</converter>
	  <min-value>1</min-value>
	  <max-value>10</max-value>
	</validation>
      </container>
    </search-param>
    
    <search-param>
      <name>name</name>
      <field>NAME</field>
      <operator>=</operator>
      <container>
        <label>Name</label>
        <type>text</type>
        <size>128</size>
	<validation>
	  <converter>date</converter>
	  <converter-properties>
	    <property>
	      <name>pt</name>
	      <value>MM</value>
	    </property>
	    <property>
	      <name>en</name>
	      <value>MM</value>
	    </property>
	  </converter-properties>
	</validation>
      </container>
    </search-param>
  </search-params>

  <result-params>
    <result-param>
      <name>id</name>
      <search-label>Id</search-label>
      <fields>
        <field>ID</field> 
      </fields>
      <align>right</align>
      <width>45</width>
      <height>20</height>
    </result-param>
    
    <result-param>
      <name>name</name>
      <search-label>Name</search-label>
      <fields>
        <field>NAME</field>
      </fields>
      <align>left</align>
      <width>80</width>
      <height>20</height>
    </result-param>
  </result-params>
</search-metadata>
