=== mfamador/search/search-core/src/main/resources/META-INF/web-search-config_1_5.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?><!--     DTD Web Search Config v1.0     Para suportar a validação do ficheiro de configuração, é     necessário incluir o seguinte DOCTYPE no início do     ficheiro XML (depois da declaração "xml"):     <!DOCTYPE search-config PUBLIC          "-//Maisis//DTD Search Configuration 1.5//EN"          "http://www.maisis.pt/search/dtds/web-search-config_1_5.dtd">--><!ENTITY % scope  "request|session"><!ENTITY % boolean  "true|false"><!ELEMENT web-search-config  (exporter*, search+)><!--  O elemento "exporter" permite definir uma implementação  expecífica de pt.maisis.search.export.SearchResultExporter.  name        nome que poderá ser utilizado para referenciar              o "exporter".  class       implementação de              pt.maisis.search.export.SearchResultExporter.  template  velocity    identifica se a template referida no atributo              "template" deve ser "parsed" utilizando a              framework velocity.  html-header  html-footer--><!ELEMENT exporter EMPTY><!ATTLIST exporter  name                CDATA       #REQUIRED  class               CDATA       #REQUIRED  template            CDATA       #REQUIRED  velocity            (%boolean;) "true"  html-header         CDATA       #IMPLIED  html-footer         CDATA       #IMPLIED><!--  O elemento "search" representa uma pesquisa.  Atributos:  name                nome da pesquisa. Este nome deve corresponder                      a uma pesquisa já pré-configurada.  search-view         Nome da view (com o formulário da pesquisa)                      que deve ser apresentada.  search-form         Nome do atributo (request ou sessão) em que                      a form (bean que é "populated" com os                      params de pesquisa e campos de retorno)                      será guardada.  search-form-scope   Scope em que a form será colocada (request                      ou session).  search-form-class   Pode existir a necessidade de extender o                      funcionamento da form. Nestes casos poderá                      ser criada uma classe específica que irá                      substituir a classe da form actual.  search-result       Nome do atributo que será utilizado para                      colocar o resultado da pesquisa no request                      ou na sessão  search-result-scope Scope em que onde o resultado da pesquisa                      será colocado.--><!ELEMENT search (result-view)*><!ATTLIST search  name                 CDATA      #REQUIRED  search-view          CDATA      #REQUIRED  result-view          CDATA      #REQUIRED  search-form          CDATA      #IMPLIED  search-form-scope    (%scope;)  "request"  search-form-class    CDATA      "pt.maisis.search.web.SearchForm"  search-result        CDATA      "result"  search-result-scope  (%scope;)  "request"  count                CDATA      #IMPLIED  result-record-limit  CDATA      #IMPLIED  query-timeout        CDATA      #IMPLIED  select-all-result-params CDATA  "true"  hide-duplicated-result-params CDATA "false"  hide-duplicated-html-result-params CDATA "false"  exporter-filename-prefix CDATA  #IMPLIED  exporter-compression CDATA      #IMPLIED  exporter-compression-record CDATA #IMPLIED><!ELEMENT result-view EMPTY><!ATTLIST result-view  format               CDATA      #REQUIRED  name                 CDATA      #REQUIRED>

=== mfamador/search/search-example/src/main/resources/web-search-config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!DOCTYPE web-search-config PUBLIC 
"-//Maisis//DTD Web Search Config 1.5//EN" 
"http://www.maisis.pt/search/dtds/web-search-config_1_5.dtd">

<web-search-config>

  <exporter
      name="exporter"
      class="pt.maisis.search.export.jfreereport.SearchResultExporter"
      velocity="true"
      template="search-jfreereport.xml"/>

  <search
      name="search1"
      search-form="searchForm"
      search-form-scope="session"
      search-view="search1.jsp"
      result-view="exporter">
    <result-view format="html" name="search1.jsp"/>
  </search>

  <search 
      name="search2"
      search-form="searchForm"
      search-form-scope="session"
      search-view="search2.jsp"
      result-view="exporter"
      count="10"
      select-all-result-params="true">
    <result-view format="html" name="search2.jsp"/>
  </search>

  <search 
      name="search3"
      search-form="searchForm"
      search-form-scope="session"
      search-view="search3.jsp"
      result-view="exporter"
      count="10"
      select-all-result-params="true">
    <result-view format="html" name="search3.jsp"/>
  </search>
</web-search-config>
